/* generated by bootloader.pl */
#define BOOTLOADER_FREQ_KHZ 50000
#define BOOTLOADER_SRAMSZ_KB 0
#define BOOTLOADER_SDRAMSZ_MB 32
#define BOOTLOADER_BAUD 38400
#define CONFIG_KERNEL_COMMAND_LINE "console=ttyS0,38400"

#define BOOTLOADER_memcfg1  0x877
#define BOOTLOADER_memcfg2  0x89a06020
#define BOOTLOADER_uart     0xa3
#define BOOTLOADER_loopback 0x0
#define BOOTLOADER_flow     0x0
#define BOOTLOADER_ftreg    0x189000

#define BOOTLOADER_grlib_sdram 0x89a00189
#define BOOTLOADER_ddr2spa_cfg1 0x95008616
#define BOOTLOADER_ddr2spa_cfg3 0x13650000
#define BOOTLOADER_ddrspa_cfg1 0xfd008616

#define BOOTLOADER_freq      50500000

#define BOOTLOADER_ramsize   0x1fff000
#define BOOTLOADER_romsize   0x2000
#define BOOTLOADER_stack     0x70800000

#define BOOTLOADER_physbase  0x70000000
