#!/bin/sh
mount -t proc none /proc
mount -t sysfs none /sys
mount -t devpts devpts /dev/pts
mount -t tmpfs -o size=1M tmpfs /var/tmp

hostname DMV02

/sbin/ifconfig lo up 127.0.0.1 netmask 255.0.0.0
/sbin/ifconfig eth0 up 10.21.30.66

route add 127.0.0.1 dev lo
route add default dev eth0

/bin/portmap &

# Mount nfs export with rw supportfrom 10.21.30.49,
# DO NOT FORGET: start the nfs server on 10.21.30.49
mount -o nolock -o rw -t nfs 10.21.30.49:/localdisk/local_users/orfanosm/nfs /home/nfs
